" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" activate pathogen plugin loader
execute pathogen#infect()

set t_Co=256
if $TERM ==# "xterm-256color"
	set termguicolors
end
"let g:libertine_Midnight = 1
"let g:libertine_Sunset = 1
"colorscheme libertine
colorscheme monokai

"set statusline+=%{fugitive#statusline()}
set laststatus=2

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

set backup		" keep a backup file (restore to previous version)
set undofile		" keep an undo file (undo changes after closing)
set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set incsearch		" do incremental searching
set nu			" show line numbers in gutter
set relativenumber	" show relative numberinf
syntax on		" activate syntax highlighting
set hlsearch		" highlight search results

" syntastic settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" highlighting the cursor line
"set cursorline
"hi cursorline cterm=none
"hi cursorlinenr ctermfg=red
"hi cursorim guifg=#192224 guibg=#536991 guisp=#536991 gui=NONE ctermfg=235 ctermbg=60 cterm=NONE

" Airling settings
" Enable the list of buffers
let g:airline#extensions#tabline#enabled = 1
" Show just the filename
let g:airline#extensions#tabline#fnamemod = ':t'

" Ctrl-p settings
let g:ctrlp_max_files=20000
let g:ctrlp_custom_ignore='.git$|\tmp$|node_modules$|target$|dist$'
let g:ctrlp_root_markers = ['ivy.xml']

" Key mappings
let mapleader = ","
" Remap keys to switch buffers faster
nnoremap <C-S> :bprevious<CR>
nnoremap <C-D> :bnext<CR>
" Toggle NERDTree
nnoremap <Leader>t :NERDTreeToggle<CR> 
nnoremap <Leader>s :SyntasticToggleMode<CR>
vnoremap <Leader>k :w !pbcopy<CR><CR>

au BufReadPost *.conf set syntax=conf

"let g:ctrlp_working_path_mode = 'ra'

