#!/bin/sh

# backup existing
if [ ! -f /etc/pf.conf.original ]
then
  echo "Backing up original pf.conf"
  sudo cp /etc/pf.conf /etc/pf.conf.original
fi

# install the configuration
echo "Installing root pf.conf"
sudo cp pf.conf /etc/pf.conf

echo "Installing anchor"
# Download the list of IPs to block
curl -O http://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt
sudo cp pf-philippe.conf /etc/pf.anchors/pf-philippe.conf
sudo cp emerging-Block-IPs.txt /etc/pf.anchors/emerging-Block-IPs.txt

echo "Installing daemon"
sudo cp philippe.pf.plist /Library/LaunchDaemons/

echo "Restarting pf"
sudo pfctl -d
sudo pfctl -e -f /etc/pf.conf

