alias start-ssh-agent='eval $(ssh-agent -s)'
alias todo='vim ~/todo.txt'
alias aiv='cd ~/w_aiv'
alias updateports='sudo port selfupdate && sudo port upgrade outdated'
alias mvntree='mvn dependency:tree'
alias develop='git checkout develop'
alias master='git checkout master'
