" File: vimrc
"
" Author: Philippe Schottey
"
"
" PLUGINS
"

" Works only on *nix
if (!has('win32')) 
  let data_dir = '~/.vim'
  if empty(glob(data_dir . '/autoload/plug.vim'))
    silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
  endif
endif

call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'
Plug 'editorconfig/editorconfig-vim'
Plug 'jiangmiao/auto-pairs'
Plug 'kien/ctrlp.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'airblade/vim-gitgutter'
Plug 'freitass/todo.txt-vim'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'chrisbra/csv.vim'
Plug 'fourjay/vim-hurl'
Plug 'dhruvasagar/vim-table-mode'
Plug 'arcticicestudio/nord-vim'
" snipMate
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'tomtom/tlib_vim'
Plug 'garbas/vim-snipmate' 
" themes
Plug 'dracula/vim',{'as':'dracula'}
Plug 'whatyouhide/vim-gotham'
Plug 'sainnhe/everforest'
Plug 'sainnhe/edge'
call plug#end()

" 
" OPTIONS
"
set nocompatible
set relativenumber
set number
set helpheight=30
set cursorline
set backspace=indent,eol,start
set hlsearch	" highlight all matches
set incsearch	" highlight search results as you type
set noswapfile
set path=.,,**
set listchars=tab:>-
set list
set termguicolors
set belloff=all

"
" FILES
"
filetype plugin indent on
syntax enable

"
" FEEL
"
let mapleader=","
nnoremap <Leader>e :Explore<CR>
nnoremap <Backspace> :nohl<CR>
nnoremap <F3> [<c-I><CR>
nnoremap <c-b> :CtrlPBuffer<CR>
" nnoremap <c-b> <c-]>
" Deactivate the arrows
map <Down> <Nop>
map <Up> <Nop>
map <Left> <Nop>
map <Right> <Nop>
imap <Down> <Nop>
imap <Up> <Nop>
imap <Left> <Nop>
imap <Right> <Nop>
" Mappings to resize panes 
nnoremap <Leader>ss :vertical resize -4<CR>
nnoremap <Leader>ww :vertical resize +4<CR>
nnoremap ; A;<Esc>
vmap <Leader>c :w ! xsel -i -b<CR><CR>
" To uppercase
inoremap <c-u> <esc>gUiwea
" Allow tab to autocomplete first suggestion
inoremap <silent><expr> <cr> coc#pum#visible() ? coc#_select_confirm() : "\<C-g>u\<CR>"

" NETRW
"
let g:netrw_hide=1
let g:netrw_browsex_viewer="open"
let g:netrw_liststyle=1
let g:netrw_keepdir=1
let g:netrw_maxfilenamelen=66

" 
" LOOKS
" 
set background=dark
colorscheme dracula
call matchadd('ColorColumn', '\%81v')
let &t_ut=''
set laststatus=2
if has("gui_running")
  set guifont=Hack\ 12
  set guioptions-=T
endif

"
" PLUGIN CTRLP
"
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_max_files=20000
let g:ctrlp_custom_ignore='\v[\/]((\.(git|hg|svn))|(target|dist|node_modules|build|bin|vendor)|(.*\~))$'
let g:ctrlp_root_markers = ['ivy.xml', 'build.gradle', 'composer.json', 'package.json', 'build.xml']
let g:ctrlp_show_hidden = 1
let g:ctrlp_working_path_mode = ''

"
" PLUGIN SNIPMATE
"
let g:snipMate = { 'snippet_version' : 1 }

