" File: vimrc
"
" Author: Philippe Schottey
"
echo "// Booting up vim... (^_^)"

"
" PLUGINS
"
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'
Plug 'editorconfig/editorconfig-vim'
Plug 'dag/vim-fish'
Plug 'jiangmiao/auto-pairs'
" themes
Plug 'pgavlin/pulumi.vim'
Plug 'kamykn/dark-theme.vim'
call plug#end()

" 
" OPTIONS
"
set nocompatible
set relativenumber
set helpheight=30
set cursorline
set backspace=indent,eol,start
set hlsearch	" highlight all matches
set incsearch	" highlight search results as you type
set noswapfile
set path=.,,**
set listchars=tab:>-
set list

"
" FILES
"
filetype plugin indent on
syntax enable

"
" FEEL
"
let mapleader=","
nnoremap <Leader>e :Lexplore<CR>
nnoremap <Backspace> :nohl<CR>
" Deactivate the arrows
map <Down> <Nop>
map <Up> <Nop>
map <Left> <Nop>
map <Right> <Nop>
imap <Down> <Nop>
imap <Up> <Nop>
imap <Left> <Nop>
imap <Right> <Nop>

"   
" NETRW
"
let g:netrw_winsize=20
let g:netrw_hide=0
let g:netrw_browsex_viewer="open"
let g:netrw_liststyle=3
let g:netrw_keepdir=1

" 
" LOOKS
" 
" hi CursorLineNr ctermfg=magenta
" hi LineNr ctermfg=gray
" hi StatusLineNC ctermfg=black ctermbg=gray
colorscheme pulumi
call matchadd('ColorColumn', '\%81v')

" 
" STATUSLINE
"
set laststatus=2
set statusline=(%n)\ %.20f\ %y\ [%{GetFileEncoding()}]\ [%{GetFileFormat()}]\ %m
set statusline+=%=
set statusline+=
set statusline+=%c:%l\ (%L)
set statusline+=\ %P

function! GetFileEncoding()
  return &fileencoding
endfunction

function! GetFileFormat()
  return &fileformat
endfunction

"
" ====================
" PLUGIN CTRLP
" ====================
let g:ctrlp_max_files=20000
" let g:ctrlp_custom_ignore='.*(\.git\|\.hg\|\.svn\|\~\|target\|node_modules\|build\|\.class\|bin)$'
let g:ctrlp_custom_ignore='\v[\/]((\.(git|hg|svn))|(target|dist|node_modules|build|bin|vendor)|(.*\~))$'
let g:ctrlp_root_markers = ['ivy.xml', 'build.gradle', 'composer.json', 'package.json', 'build.xml']
let g:ctrlp_show_hidden = 1
let g:ctrlp_working_path_mode = ''
